/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'totalTasks' : bigint,
  'pendingWithdrawalRequests' : bigint,
  'totalWithdrawalRequests' : bigint,
  'totalEarningsDistributed' : Balance,
  'totalUsers' : bigint,
}
export type Balance = bigint;
export type PaymentMethod = { 'easypaisa' : null } |
  { 'jazzcash' : null };
export interface Task {
  'id' : TaskId,
  'reward' : Balance,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'completedCount' : bigint,
}
export interface TaskDto {
  'id' : TaskId,
  'reward' : Balance,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'completedCount' : bigint,
}
export type TaskId = bigint;
export type Time = bigint;
export interface UserDashboard {
  'availableTasks' : Array<TaskDto>,
  'completedTasks' : Array<TaskDto>,
  'earnings' : Balance,
}
export interface UserProfile {
  'name' : string,
  'earnings' : Balance,
  'withdrawalCount' : bigint,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserWithEarnings {
  'principal' : Principal,
  'name' : string,
  'earnings' : Balance,
}
export type WithdrawalId = bigint;
export interface WithdrawalRequestDto {
  'id' : WithdrawalId,
  'status' : WithdrawalStatus,
  'userName' : string,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Time,
  'user' : Principal,
  'phoneNumber' : string,
  'amount' : Balance,
}
export type WithdrawalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveWithdrawal' : ActorMethod<[WithdrawalId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeTask' : ActorMethod<[TaskId], undefined>,
  'createTask' : ActorMethod<[string, string, Balance], TaskId>,
  'deleteTask' : ActorMethod<[TaskId], undefined>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllTasksWithCompletions' : ActorMethod<[], Array<Task>>,
  'getAllUsersWithEarnings' : ActorMethod<[], Array<UserWithEarnings>>,
  'getAllWithdrawals' : ActorMethod<[], Array<WithdrawalRequestDto>>,
  'getAvailableTasks' : ActorMethod<[], Array<TaskDto>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletedTasks' : ActorMethod<[], Array<TaskDto>>,
  'getCurrentEarnings' : ActorMethod<[], Balance>,
  'getMyWithdrawals' : ActorMethod<[], Array<WithdrawalRequestDto>>,
  'getTask' : ActorMethod<[TaskId], TaskDto>,
  'getUserDashboard' : ActorMethod<[], UserDashboard>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rejectWithdrawal' : ActorMethod<[WithdrawalId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitWithdrawal' : ActorMethod<
    [Balance, string, PaymentMethod],
    WithdrawalId
  >,
  'updateTask' : ActorMethod<[TaskId, string, string, Balance], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];