/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const WithdrawalId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TaskId = IDL.Nat;
export const Balance = IDL.Nat;
export const AdminStats = IDL.Record({
  'totalTasks' : IDL.Nat,
  'pendingWithdrawalRequests' : IDL.Nat,
  'totalWithdrawalRequests' : IDL.Nat,
  'totalEarningsDistributed' : Balance,
  'totalUsers' : IDL.Nat,
});
export const Time = IDL.Int;
export const Task = IDL.Record({
  'id' : TaskId,
  'reward' : Balance,
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'completedCount' : IDL.Nat,
});
export const UserWithEarnings = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'earnings' : Balance,
});
export const WithdrawalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'easypaisa' : IDL.Null,
  'jazzcash' : IDL.Null,
});
export const WithdrawalRequestDto = IDL.Record({
  'id' : WithdrawalId,
  'status' : WithdrawalStatus,
  'userName' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'phoneNumber' : IDL.Text,
  'amount' : Balance,
});
export const TaskDto = IDL.Record({
  'id' : TaskId,
  'reward' : Balance,
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'completedCount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'earnings' : Balance,
  'withdrawalCount' : IDL.Nat,
});
export const UserDashboard = IDL.Record({
  'availableTasks' : IDL.Vec(TaskDto),
  'completedTasks' : IDL.Vec(TaskDto),
  'earnings' : Balance,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveWithdrawal' : IDL.Func([WithdrawalId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeTask' : IDL.Func([TaskId], [], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Text, Balance], [TaskId], []),
  'deleteTask' : IDL.Func([TaskId], [], []),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllTasksWithCompletions' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllUsersWithEarnings' : IDL.Func(
      [],
      [IDL.Vec(UserWithEarnings)],
      ['query'],
    ),
  'getAllWithdrawals' : IDL.Func(
      [],
      [IDL.Vec(WithdrawalRequestDto)],
      ['query'],
    ),
  'getAvailableTasks' : IDL.Func([], [IDL.Vec(TaskDto)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletedTasks' : IDL.Func([], [IDL.Vec(TaskDto)], ['query']),
  'getCurrentEarnings' : IDL.Func([], [Balance], ['query']),
  'getMyWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalRequestDto)], ['query']),
  'getTask' : IDL.Func([TaskId], [TaskDto], ['query']),
  'getUserDashboard' : IDL.Func([], [UserDashboard], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectWithdrawal' : IDL.Func([WithdrawalId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitWithdrawal' : IDL.Func(
      [Balance, IDL.Text, PaymentMethod],
      [WithdrawalId],
      [],
    ),
  'updateTask' : IDL.Func([TaskId, IDL.Text, IDL.Text, Balance], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const WithdrawalId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TaskId = IDL.Nat;
  const Balance = IDL.Nat;
  const AdminStats = IDL.Record({
    'totalTasks' : IDL.Nat,
    'pendingWithdrawalRequests' : IDL.Nat,
    'totalWithdrawalRequests' : IDL.Nat,
    'totalEarningsDistributed' : Balance,
    'totalUsers' : IDL.Nat,
  });
  const Time = IDL.Int;
  const Task = IDL.Record({
    'id' : TaskId,
    'reward' : Balance,
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'completedCount' : IDL.Nat,
  });
  const UserWithEarnings = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'earnings' : Balance,
  });
  const WithdrawalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'easypaisa' : IDL.Null,
    'jazzcash' : IDL.Null,
  });
  const WithdrawalRequestDto = IDL.Record({
    'id' : WithdrawalId,
    'status' : WithdrawalStatus,
    'userName' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'phoneNumber' : IDL.Text,
    'amount' : Balance,
  });
  const TaskDto = IDL.Record({
    'id' : TaskId,
    'reward' : Balance,
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'completedCount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'earnings' : Balance,
    'withdrawalCount' : IDL.Nat,
  });
  const UserDashboard = IDL.Record({
    'availableTasks' : IDL.Vec(TaskDto),
    'completedTasks' : IDL.Vec(TaskDto),
    'earnings' : Balance,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveWithdrawal' : IDL.Func([WithdrawalId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeTask' : IDL.Func([TaskId], [], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Text, Balance], [TaskId], []),
    'deleteTask' : IDL.Func([TaskId], [], []),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllTasksWithCompletions' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllUsersWithEarnings' : IDL.Func(
        [],
        [IDL.Vec(UserWithEarnings)],
        ['query'],
      ),
    'getAllWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequestDto)],
        ['query'],
      ),
    'getAvailableTasks' : IDL.Func([], [IDL.Vec(TaskDto)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletedTasks' : IDL.Func([], [IDL.Vec(TaskDto)], ['query']),
    'getCurrentEarnings' : IDL.Func([], [Balance], ['query']),
    'getMyWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalRequestDto)],
        ['query'],
      ),
    'getTask' : IDL.Func([TaskId], [TaskDto], ['query']),
    'getUserDashboard' : IDL.Func([], [UserDashboard], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectWithdrawal' : IDL.Func([WithdrawalId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitWithdrawal' : IDL.Func(
        [Balance, IDL.Text, PaymentMethod],
        [WithdrawalId],
        [],
      ),
    'updateTask' : IDL.Func([TaskId, IDL.Text, IDL.Text, Balance], [], []),
  });
};

export const init = ({ IDL }) => { return []; };